# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/finsets',
                'doc_host': 'https://ionmihai.github.io',
                'git_url': 'https://github.com/ionmihai/finsets',
                'lib_path': 'finsets'},
  'syms': {'finsets.wrds_compa': {'finsets.wrds_compa.common_raw_vars': ('wrds_compa.html#common_raw_vars', 'finsets/wrds_compa.py')}}}
