# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/wrds_links.ipynb.

# %% auto 0
__all__ = ['gvkey_permno_m', 'gvkey_permno_a', 'gvkey_permno_q']

# %% ../nbs/wrds_links.ipynb 3
import pandas as pd

import pandasmore as pdm
from . import wrds_utils
from . import wrds2 as wrds  

# %% ../nbs/wrds_links.ipynb 6
def gvkey_permno_m(wrds_username: str=None) -> pd.DataFrame:
    """CRSP Monthly ids, with gvkeys"""

    sql_string="""SELECT a.date, a.permno, c.gvkey
                  FROM crsp.msf a
                  INNER JOIN crsp.msenames b ON a.permno = b.permno
                                             AND a.date BETWEEN b.namedt AND b.nameendt 
                  INNER JOIN crsp.ccmxpf_lnkhist c ON a.permno = c.lpermno 
                                                   AND c.linktype IN ('LU','LC') AND c.linkprim IN ('P','C')
                                                   AND a.date BETWEEN c.linkdt AND COALESCE(c.linkenddt, CURRENT_DATE)"""
    
    df = wrds_utils.download(sql_string, wrds_username)
    df = pdm.setup_panel(df, panel_ids='permno', time_var='date', freq='M',
                         drop_index_duplicates=True, duplicates_which_keep='last')
    df['gvkey'] = df['gvkey'].astype('string')
    return df.reset_index()[['permno','Mdate','gvkey']].copy()  

# %% ../nbs/wrds_links.ipynb 9
def gvkey_permno_a(wrds_username: str=None) -> pd.DataFrame:
    """qvkey to permno correspondence at the annual frequency. As done by CCM."""

    sql_string=f"""SELECT a.datadate, a.gvkey , b.lpermno as permno
                    FROM comp.funda a
                    INNER JOIN crsp.ccmxpf_lnkhist  b ON a.gvkey = b.gvkey
                    WHERE datadate BETWEEN b.linkdt AND COALESCE(b.linkenddt, CURRENT_DATE)
                            AND b.linktype IN ('LU','LC') AND b.linkprim IN ('P','C')
                            AND indfmt='INDL' AND datafmt='STD' AND popsrc='D' AND consol='C'"""
    
    df = wrds_utils.download(sql_string, wrds_username)
    df = pdm.setup_panel(df, panel_ids='permno', time_var='datadate', freq='A',
                         drop_index_duplicates=True, duplicates_which_keep='last')
    df['gvkey'] = df['gvkey'].astype('string')
    return df.reset_index()[['permno','Adate','gvkey']].copy()  

# %% ../nbs/wrds_links.ipynb 12
def gvkey_permno_q(wrds_username: str=None) -> pd.DataFrame:
    """qvkey to permno correspondence at the quarterly frequency. As done by CCM."""
    
    sql_string=f"""SELECT a.datadate, a.gvkey , b.lpermno as permno
                    FROM comp.fundq a
                    INNER JOIN crsp.ccmxpf_lnkhist  b ON a.gvkey = b.gvkey
                    WHERE datadate BETWEEN b.linkdt AND COALESCE(b.linkenddt, CURRENT_DATE)
                            AND b.linktype IN ('LU','LC') AND b.linkprim IN ('P','C')
                            AND indfmt='INDL' AND datafmt='STD' AND popsrc='D' AND consol='C'"""
    
    df = wrds_utils.download(sql_string, wrds_username)
    df = pdm.setup_panel(df, panel_ids='permno', time_var='datadate', freq='Q',
                         drop_index_duplicates=True, duplicates_which_keep='last')
    df['gvkey'] = df['gvkey'].astype('string')
    return df.reset_index()[['permno','Qdate','gvkey']].copy()    
