# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/wrds_utils.ipynb.

# %% auto 0
__all__ = ['download']

# %% ../nbs/wrds_utils.ipynb 2
from typing import Sequence
import os, glob 

import pandas as pd
from . import wrds2 as wrds  

# %% ../nbs/wrds_utils.ipynb 11
def download(sql_string: str=None,
             wrds_username: str=None, #If None, looks for WRDS_USERNAME with `os.getenv`; prompts you if it can't find it
             params: Sequence=None # Params cited in the `sql_string`
             ) -> pd.DataFrame:
    """Downloads data from WRDS using the given PostgreSQL `sql_string`"""

    if wrds_username is None:
        wrds_username = os.getenv('WRDS_USERNAME')
        if wrds_username is None: wrds_username = input("Enter your WRDS username: ") 

    with wrds.Connection(wrds_username = wrds_username) as db:
        return db.raw_sql(sql=sql_string, params=params)
