# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/wrds_links.ipynb.

# %% auto 0
__all__ = ['crspm_w_gvkey', 'compa_w_permno']

# %% ../nbs/wrds_links.ipynb 3
import pandas as pd

from . import wrds_utils

# %% ../nbs/wrds_links.ipynb 6
def crspm_w_gvkey(wrds_username: str=None) -> pd.DataFrame:
    """CRSP Monthly ids, with gvkeys"""

    sql_string="""SELECT a.date, a.permno, a.permco, c.gvkey, c.liid as iid
                  FROM crsp.msf a
                  INNER JOIN crsp.msenames b ON a.permno = b.permno
                                             AND a.date BETWEEN b.namedt AND b.nameendt 
                  INNER JOIN crsp.ccmxpf_lnkhist c ON a.permno = c.lpermno 
                                                   AND c.linktype IN ('LU','LC') AND c.linkprim IN ('P','C')
                                                   AND a.date BETWEEN c.linkdt AND COALESCE(c.linkenddt, CURRENT_DATE)
                """
    return wrds_utils.download(sql_string, wrds_username)

# %% ../nbs/wrds_links.ipynb 9
def compa_w_permno(wrds_username: str=None) -> pd.DataFrame:
    """COMPUSTAT Fundamentals Annual with permno's. As done by CCM."""
    sql_string=f"""SELECT a.datadate, a.gvkey , b.lpermno as permno, b.lpermco as permco, b.liid as iid 
                    FROM comp.funda a
                    INNER JOIN crsp.ccmxpf_lnkhist  b ON a.gvkey = b.gvkey
                    WHERE datadate BETWEEN b.linkdt AND COALESCE(b.linkenddt, CURRENT_DATE)
                            AND b.linktype IN ('LU','LC') AND b.linkprim IN ('P','C')
                            AND indfmt='INDL' AND datafmt='STD' AND popsrc='D' AND consol='C'"""
    
    return wrds_utils.download(sql_string, wrds_username)
